# Generated by Django 4.1.6 on 2023-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieZoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
