# Generated by Django 4.1.6 on 2023-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieZoneApp', '0002_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
